name: docs

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - "pytorch_wheel_installer/**"
      - "docs/**"
      - "requirements-dev.txt"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools

      - name: Install latex requirements
        run: |
          sudo apt update -y
          sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Build documentation
        run: tox -e docs

      - name: Upload html build
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: docs/build/html

      - name: Upload latex build
        uses: actions/upload-artifact@v2
        with:
          name: latex
          path: docs/build/latex/pytorch_wheel_installer.pdf
