name: publish

on:
  release:
    types: [created]

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install setuptools wheel twine

      - name: Build tarball and wheel
        run: python setup.py sdist bdist_wheel

      - name: Upload to PyPI
        env:
          TWINE_REPOSITORY: pypi
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
