name: tests

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - "pytorch_wheel_installer/**"
      - "tests/**"
      - "pytest.ini"
      - "tox.ini"
      - "codecov.yml"
      - "requirements-dev.txt"
      - ".github/workflows/tests.yml"

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.6, 3.7, 3.8]
      fail-fast: true

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade and install additional system packages
        run: pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: tox -e py -- --skip-large-download

      - name: Upload coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          env_vars: OS,PYTHON

  tox_plugin_smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Upgrade and install additional system packages
        run: pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install tox
        run: pip install tox

      - name: Install pytorch_wheel_installer
        run: pip install .

      - name: Test tox for smoke
        run: tox --help
